version: '3'
services:
  web:
    build: .
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
    volumes:
      - ./webserver:/var/webserver
    stdin_open: true
    tty: true